<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\OpenAITunnelManager.Core\OpenAITunnelManager.Core.csproj" />
    <ProjectReference Include="..\..\src\OpenAITunnelManager.Infrastructure\OpenAITunnelManager.Infrastructure.csproj" />
    <ProjectReference Include="..\OpenAITunnelManager.FakeTunnelClient\OpenAITunnelManager.FakeTunnelClient.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
</Project>
